# Default values for kafdrop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Image Info
## ref: https://hub.docker.com/r/confluentinc/cp-kafka-connect
image:
  registry: docker.io
  repository: obsidiandynamics/kafdrop
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets:  []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

## Kafdrop Configuration
## ref: https://docs.confluent.io/platform/current/connect/references/allconfigs.html
heapOpts: -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0
service:
  type: NodePort
  port: 9000
  nodePort: 30900

  ## Kafka Cluster Configuration
kafka:
  ## If true, kafka was installed under the same umbrella
  enabled: false
  ## If outside or custom kafka a bootstrap server is required
  bootstrapServers: kafka.async-course.svc.cluster.local:9092

## Schema Registry Configuration
schema-registry:
  ## If true, schema-registry was installed under the same umbrella
  enabled: true
  ## If outside or custom a URL and port are required to connect
  url:

## Configure Liveness and Readiness Probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Configure Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  fsGroup: 1000

## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
    - ALL

## Configure Resources for Containers
## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: 
  limits:
    cpu: 400m
    memory: 440Mi
  requests:
    cpu: 100m
    memory: 220Mi